[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' http://localhost:5173 https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: blob: https://*.googleapis.com https://*.google.com https://img.youtube.com https://firebase.googleapis.com https://firebasestorage.googleapis.com https://*.cloudflare.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.googleapis.com wss://*.firebaseio.com https://*.firebaseio.com https://firestore.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com; frame-src 'self' https://www.youtube.com https://www.buymeacoffee.com; manifest-src 'self'; base-uri 'self'; form-action 'self'; media-src 'self'; worker-src 'self' blob:; frame-ancestors 'none'; upgrade-insecure-requests;"

[[forms]]
  name = "contact"
